(function(c){c.fn.jPaginator=function(o){this.size()!=1&&c.error("You must use this plugin with a unique element");var a={selectedPage:null,nbPages:100,nbVisible:10,widthPx:30,marginPx:1,overBtnLeft:null,overBtnRight:null,maxBtnLeft:null,maxBtnRight:null,withSlider:!0,withAcceleration:!0,speed:2,coeffAcceleration:2,minSlidesForSlider:3,onPageClicked:null},b={realWid:0,curNum:1,infRel:0,cInfMax:0,cInf:0,nbMove:0,isMoving:!1,isLimitL:!1,isLimitR:!1,listenSlider:!0};return this.each(function(){function s(e){e=
1*e.html();d.find(".paginator_p.selected").removeClass("selected");a.selectedPage=e;p();c(d.find(".paginator_p_bloc .paginator_p").get(a.selectedPage-b.curNum+1)).addClass("selected");a.onPageClicked&&a.onPageClicked.call(this,d,a.selectedPage)}function p(){k(a.selectedPage-Math.floor((a.nbVisible-1)/2));b.listenSlider=!1;l(b.cInf);b.listenSlider=!0}function k(e){d.find(".paginator_p.selected").removeClass("selected");var e=Math.min(a.nbPages-a.nbVisible+1,e),e=Math.max(1,e),f=e-2;d.find(".paginator_p_bloc .paginator_p").each(function(){f+=
1;c(this).html(f);a.selectedPage==f&&c(this).addClass("selected")});d.find(".paginator_p_bloc").css("left","-"+b.realWid+"px");b.curNum=e;b.cInf=(e-1)*b.realWid;b.infRel=0}function l(a){var a=Math.round(a/b.cInfMax*100),c=d.find(".paginator_slider").slider("option","value");a!=c&&d.find(".paginator_slider").slider("option","value",a)}function q(e,c){if(b.listenSlider&&!b.isMoving){var d=c.value,d=Math.min(100,d),d=Math.max(0,d),h=Math.round(b.cInfMax*d/100)-b.cInf;d==100?k(a.nbPages-a.nbVisible+1):
d==0?k(1):j(h)}}function j(e){var c=b.infRel+e,j=Math.abs(e)/e*Math.floor(Math.abs(c)/b.realWid);c%=b.realWid;b.infRel=c;var h=(b.curNum-1)*b.realWid+b.infRel,g=b.curNum+j;g<1&&(h=-1);g>a.nbPages&&(h=b.cInfMax+1);h<0?(k(1),b.cInf=0,b.infRel=0,l(0),b.isLimitL=!0,m()):h>b.cInfMax?(k(a.nbPages),b.cInf=b.cInfMax,b.infRel=0,l(b.cInfMax),b.isLimitR=!0,m()):(b.isLimitL=!1,b.isLimitR=!1,b.cInf=h,e!=0&&(j!=0&&k(g),l(b.cInf),d.find(".paginator_p_bloc").css("left",-1*c-b.realWid+"px")))}function m(){b.nbMove=
0;b.isMoving=!1}function g(a){if(!(b.isLimitR&&a=="right")&&!(b.isLimitL&&a=="left")){var c=Math.round(b.cInfMax/10);a=="left"&&(c*=-1);j(c);setTimeout(function(){b.nbMove+=1;g(a)},20)}}function n(c){if(b.isMoving){var d=Math.min(Math.abs(a.speed),5),g=Math.min(Math.abs(a.coeffAcceleration),5);a.withAcceleration&&(d=Math.round(d+Math.round(g*b.nbMove*b.nbMove/8E4)));c=="left"&&(d*=-1);j(d);setTimeout(function(){b.nbMove+=1;n(c)},10)}}function r(){var e,f;a.nbVisible=Math.min(a.nbVisible,a.nbPages);
d.find(".paginator_p_bloc > .paginator_p").remove();for(i=1;i<=a.nbVisible+2;i++)d.find(".paginator_p_bloc").append(c("<a class='paginator_p'></a>"));e=a.nbVisible<a.nbPages;a.overBtnLeft&&(e?c(a.overBtnLeft).show():c(a.overBtnLeft).hide());a.overBtnRight&&(e?c(a.overBtnRight).show():c(a.overBtnRight).hide());a.maxBtnLeft&&(e?c(a.maxBtnLeft).show():c(a.maxBtnLeft).hide());a.maxBtnRight&&(e?c(a.maxBtnRight).show():c(a.maxBtnRight).hide());e?(e=Math.ceil(a.nbPages/a.nbVisible),f=a.withSlider,(f=e<a.minSlidesForSlider?
!1:a.withSlider)?(d.find(".paginator_slider").show(),d.find(".paginator_slider").children().show()):(d.find(".paginator_slider").hide(),d.find(".paginator_slider").children().hide())):(d.find(".paginator_slider").hide(),d.find(".paginator_slider").children().hide());e=0;f=d.find(".paginator_p").first().css("border-left-width");f.indexOf("px")>0&&(e=f.replace("px","")*1);b.realWid=a.widthPx+a.marginPx*2+e*2;e=1*b.realWid*a.nbVisible;d.find(".paginator_p").css("width",a.widthPx+"px");d.find(".paginator_p").css("margin",
"0 "+a.marginPx+"px 0 "+a.marginPx+"px");d.find(".paginator_p_wrap").css("width",e+"px");d.find(".paginator_slider").css("width",e+"px");b.cInfMax=a.nbPages*b.realWid-a.nbVisible*b.realWid;a.selectedPage=Math.min(a.selectedPage,a.nbPages);p();j(0);a.selectedPage&&c(d.find(".paginator_p_bloc .paginator_p").get(a.selectedPage-b.curNum+1)).addClass("selected");d.find(".paginator_p").bind("click.jPaginator",function(){return s(c(this))})}var d=c(this);o&&c.extend(a,o);r();c(this).bind("reset",function(b,
d){c.extend(a,d);r()});a.withSlider&&(d.find(".paginator_slider").slider({animate:!1}),d.find(".paginator_slider").bind("slidechange.jPaginator",function(a,b){return q(a,b)}),d.find(".paginator_slider").bind("slide.jPaginator",function(a,b){return q(a,b)}));a.overBtnLeft&&c(a.overBtnLeft).bind("mouseenter.jPaginator",function(){c(this);b.isMoving=!0;n("left")});a.overBtnLeft&&c(a.overBtnLeft).bind("mouseleave.jPaginator",function(){c(this);m()});a.overBtnRight&&c(a.overBtnRight).bind("mouseenter.jPaginator",
function(){c(this);b.isMoving=!0;n("right")});a.overBtnRight&&c(a.overBtnRight).bind("mouseleave.jPaginator",function(){c(this);m()});a.maxBtnLeft&&c(a.maxBtnLeft).bind("click.jPaginator",function(){return g("left")});a.maxBtnRight&&c(a.maxBtnRight).bind("click.jPaginator",function(){return g("right")});d.find(".paginator_p").bind("mouseenter.jPaginator",function(){var a=c(this);d.find(".paginator_p.over").removeClass("over");a.addClass("over")});d.find(".paginator_p").bind("mouseleave.jPaginator",
function(){c(this);d.find(".paginator_p.over").removeClass("over")})})}})(jQuery);